### ISSUE TITLE
Bits

### ISSUE THREAD

**Issue by Andyvff** [AV-86/Reed-Solomon-Demo#1]
Привет.
Планируете ли вы добавить в программу работу не с 8 битами, а с меньшим числом бит. например 6. ну или может галочку с выбором битов?

**Comment by AV-86** [comment]
Приветствую! Думаю, что я врядли стану заниматься допиливанием этой программы. Она была как пояснение к циклу статей на хабре: [https://habr.com/ru/post/528142/](https://habr.com/ru/post/528142/). Можете ознакомиться и сами реализовать 6 или 5 или сколько хотите битное кодирование - исходный код открыт, старался коментировать и писать просто.
